package julianh06.wynnextras.features.abilitytree;

import java.util.ArrayList;
import java.util.Arrays;

public class CheckPageOfAbility {
    public ArrayList Page1 = new ArrayList<>(Arrays.asList(
            "Arrow Bomb",
            "Bash",
            "Bow Proficiency",
            "Cheaper Arrow Bomb",
            "Cheaper Bash",
            "Cheaper Meteor",
            "Cheaper Spin Attack",
            "Cheaper Totem",
            "Dagger Proficiency I",
            "Double Bash",
            "Double Spin",
            "Heart Shatter",
            "Meteor",
            "Relik Proficiency I",
            "Shooting Star",
            "Spear Proficiency I",
            "Spin Attack",
            "Totem",
            "Totemic Smash",
            "Wand Proficiency I"
    ));

    public ArrayList Page2 = new ArrayList<>(Arrays.asList(
            "Arrow Shield",
            "Arrow Storm",
            "Aura",
            "Charge",
            "Cheaper Charge",
            "Cheaper Dash",
            "Cheaper Escape",
            "Cheaper Haul",
            "Cheaper Teleport",
            "Dash",
            "Distant Grasp",
            "Double Shots",
            "Double Slice",
            "Escape",
            "Hand of the Shaman",
            "Haul",
            "Heal",
            "Heavy Impact",
            "Ice Snake",
            "Multihit",
            "Poisoned Blade",
            "Power Shots",
            "Smoke Bomb",
            "Sticky Bomb",
            "Teleport",
            "Totem Shove",
            "Tougher Skin",
            "Uppercut",
            "Uproot",
            "Vehement",
            "Wand Proficiency II",
            "War Scream",
            "Windy Feet",
            "Wisdom"
    ));

    public ArrayList Page3 = new ArrayList<>(Arrays.asList(
            "Air Mastery",
            "Backstab",
            "Bamboozle",
            "Bryophyte Roots",
            "Buckshot",
            "Burning Sigil",
            "Crashing Comet",
            "Earth Mastery",
            "Fire Creep",
            "Fire Mastery",
            "Fireworks",
            "Flaming Tongue",
            "Flaming Uppercut",
            "Flyby Jab",
            "Frenzy",
            "Half-Moon Swipe",
            "Hop",
            "Iron Lungs",
            "Nature's Jolt",
            "Nimble String",
            "Overseer",
            "Phantom Ray",
            "Quadruple Bash",
            "Rain Dance",
            "Ripple",
            "Shocking Aura",
            "Sunshower",
            "Thunder Mastery",
            "Thunderstorm",
            "Triple Shots",
            "Vanish",
            "Water Mastery",
            "Wind Slash"
    ));

    public ArrayList Page4 = new ArrayList<>(Arrays.asList(
            "Aerodynamics",
            "Air Shout",
            "Arcane Transfer",
            "Arrow Wall",
            "Arsenal Synergy",
            "Bak'al's Grasp",
            "Basaltic Trap",
            "Blood Connection",
            "Breathless",
            "Call of the Hound",
            "Cheaper Arrow Storm",
            "Cheaper Aura",
            "Cheaper Heal",
            "Cheaper Multihit",
            "Cheaper Uppercut",
            "Cheaper Uproot",
            "Counter",
            "Eye Piercer",
            "Finality",
            "Focus",
            "Foul Play",
            "Generalist",
            "Grappling Hook",
            "Guardian Angels",
            "Haunting Memory",
            "Hymn of Hate",
            "Implosion",
            "Intoxicating Blood",
            "Lacerate",
            "Larger Heal",
            "Larger Mana Bank",
            "Last Laugh",
            "Manachism",
            "Mantle of the Bovemists",
            "Mask of the Lunatic",
            "Mirage",
            "Mirror Image",
            "More Focus",
            "More Puppets",
            "Ophanim",
            "Patient Hunter",
            "Phantom Force",
            "Psithurism",
            "Puppet Master",
            "Purification",
            "Rebound",
            "Rolling Fog",
            "Sacrificial Shrine",
            "Sentient Snake",
            "Shadow Siphon",
            "Shadow Travel",
            "Shield Strike",
            "Silent Killer",
            "Spear Proficiency II",
            "Stagnation",
            "Stormy Feet",
            "Surprise Strike",
            "Totemic Reach",
            "Wall of Smoke",
            "Windstorm",
            "Windsweeper"
    ));

    public ArrayList Page5 = new ArrayList<>(Arrays.asList(
            "Arcane Restoration",
            "Black Hole",
            "Blade Fury",
            "Blazing Powder",
            "Blink",
            "Blood Pact",
            "Boiling Blood",
            "Bounding Stride",
            "Bullwhip",
            "Chant of the Lunatic",
            "Cheaper Arrow Shield",
            "Cheaper Bash II",
            "Cheaper Haul II",
            "Cheaper Ice Snake",
            "Cheaper Smoke Bomb",
            "Cheaper Teleport II",
            "Cheaper Totem II",
            "Cheaper War Scream",
            "Cleansing Breeze",
            "Collide",
            "Comet",
            "Crushing Blow",
            "Dancing Blade",
            "Divine Intervention",
            "Double Totem",
            "Duplicity",
            "Emboldening Cry",
            "Enraged Blow",
            "Exhilarate",
            "Exploding Puppets",
            "Fierce Stomp",
            "Fluid Healing",
            "Flying Kick",
            "Fortitude",
            "Freezing Sigil",
            "Grape Bomb",
            "Homing Shots",
            "Honed Shield",
            "Hoodwink",
            "Incandescence",
            "Ivyroot Mamba",
            "Larger Blood Pool",
            "Lashing Lance",
            "Leap",
            "Malicious Mockery",
            "Marked",
            "Mask of the Fanatic",
            "Masquerade",
            "Massacre",
            "More Puppets II",
            "More Traps",
            "Mutilate",
            "Orphion's Pulse",
            "Pyrokinesis",
            "Regeneration",
            "Rejuvenating Skin",
            "Resilient Light",
            "Righting Reflex",
            "Rocket Jump",
            "Sacred Surge",
            "Sandbagging",
            "Scorched Earth",
            "Seance",
            "Shocking Bomb",
            "Shrapnel Bomb",
            "Shurikens",
            "Snake Nest",
            "Storm Dance",
            "Swan Dive",
            "Totemic Shatter",
            "Transonic Warp",
            "Twain's Arc",
            "Twisted Tether",
            "Vengeful Spirit",
            "Violent Vortex",
            "Weightless"
    ));

    public ArrayList Page6 = new ArrayList<>(Arrays.asList(
            "Aerial Ace",
            "Ambush",
            "Arcane Power",
            "Arcane Speed",
            "Arctic Snake",
            "Armour Breaker",
            "Augury",
            "Axe Kick",
            "Bladestorm",
            "Blessed Bulwark",
            "Bloodier",
            "Bloodletting",
            "Bouncing Bomb",
            "Chant of the Fanatic",
            "Chaos Explosion",
            "Cheaper Arrow Shield II",
            "Cheaper Arrow Storm II",
            "Cheaper Aura II",
            "Cheaper Dash II",
            "Cheaper Escape II",
            "Cheaper Ice Snake II",
            "Cheaper Meteor II",
            "Cheaper Multihit II",
            "Cheaper Spin Attack II",
            "Commander",
            "Coursing Restraints",
            "Crimson Effigy",
            "Death Magnet",
            "Decimator",
            "Deeper Wounds",
            "Depersonalization",
            "Diffusion",
            "Dissolution",
            "Distraction",
            "Echo",
            "Eldritch Call",
            "Eviscerate",
            "Explosive Entrance",
            "Fatal Spin",
            "Fluid Healing",
            "Freestream Flow",
            "Friendly Fire",
            "Ghostly Trigger",
            "Gust",
            "Hookshot",
            "Imbued Totem",
            "Initiator",
            "Larger Mana Bank II",
            "Lightweaver",
            "Luster Purge",
            "Maddening Roots",
            "Mana Trap",
            "Mask of the Heretic",
            "Massive Bash",
            "Mindless Slaughter",
            "Misdirection",
            "More Winded",
            "Murder Flock",
            "Mythril Skin",
            "Nightcloak Knives",
            "Parting Gift",
            "Phasing Beam",
            "Provoke",
            "Psychokinesis",
            "Radiant Devotee",
            "Recycling",
            "Riposte",
            "Searing Light",
            "Seeking Totem",
            "Shadow Projection",
            "Sparkling Hope",
            "Spectral Hover",
            "Spirit of the Rabbit",
            "Tempest",
            "Time Dilation",
            "Toxic Sludge",
            "Traveler",
            "Uncontainable Corruption",
            "Vigilant Sentinels",
            "Wall Jump",
            "Whirlwind Strike"
    ));

    public ArrayList Page7 = new ArrayList<>(Arrays.asList(
            "Arcane Overflow",
            "Arrow Hurricane",
            "Awakened",
            "Beast Lore",
            "Blood Rite",
            "Blood Sorrow",
            "Bloodier II",
            "Bloodlust",
            "Brink of Madness",
            "Chant of the Heretic",
            "Cheaper Arrow Bomb II",
            "Cheaper Heal II",
            "Cheaper Smoke Bomb II",
            "Cheaper Uppercut II",
            "Cheaper Uproot II",
            "Cheaper War Scream II",
            "Chilling Snare",
            "Consecration",
            "Crepuscular Ray",
            "Cyclone",
            "Deflagrate",
            "Devitalize",
            "Devour",
            "Discombobulate",
            "Divination",
            "Elusive",
            "Everlasting Light",
            "Far Reach",
            "Frog Dance",
            "Haemorrhage",
            "Halo",
            "Harvester",
            "Heavenly Trumpet",
            "Hummingbird's Song",
            "Invigorating Wave",
            "Jasmine Bloom",
            "Larger Mana Bank III",
            "Manastorm",
            "Marked for Death",
            "Memory Recollection",
            "More Focus II",
            "More Marks",
            "More Winded II",
            "Noxious Haze",
            "Overwhelming Rage",
            "Pressure",
            "Pyrotechnics",
            "Radiance",
            "Reverberance",
            "Ricochets",
            "Sanguine Strike",
            "Satsujin",
            "Second Chance",
            "Shepherd",
            "Snow Storm",
            "Soaring Wingbeats",
            "Soul Siphon",
            "Sunflare",
            "Swift Primer",
            "Tangled Traps",
            "Thunderclap",
            "Timelock",
            "Triple Totem",
            "Windcharged"
    ));
    public static int checkpage(int currentpage, String ability){
        CheckPageOfAbility checker = new CheckPageOfAbility();

        // Check each page to find where the ability is located
        if(checker.Page1.contains(ability)){
            return 1 - currentpage;
        }
        else if(checker.Page2.contains(ability)){
            return 2 - currentpage;
        }
        else if(checker.Page3.contains(ability)){
            return 3 - currentpage;
        }
        else if(checker.Page4.contains(ability)){
            return 4 - currentpage;
        }
        else if(checker.Page5.contains(ability)){
            return 5 - currentpage;
        }
        else if(checker.Page6.contains(ability)){
            return 6 - currentpage;
        }
        else if(checker.Page7.contains(ability)){
            return 7 - currentpage;
        }

        // Return 0 if ability not found (or you could return a different value to indicate error)
        return 0;
    }
}
